validation:
  name_length: 50
  mail_max_length: 255
  pass_min_length: 6
  content_max: 140
gravatar:
  size: 80
  list: 50
  raster: 30
per_page: 10
pic_height: 400
pic_width: 400
pic_size: 5
remember_logic: "1"
expire: 2
